title: Hideki Mori's Website
description: A personal website for research activities.
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
url: "https://morihideki.github.io"
logo: /assets/images/favicon.png
